#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2020 POK team

target:
    arch: x86
    bsp: x86-qemu
    max_processors_number: 4

partitions:
    - name: pr1
      features: [timer, console, libc, shutdown]
      threads:
          count: 1
          features: []
      size: 120kB
      objects: ["main.o"]

kernel:
    features: [assert, debug]
    scheduler:
        major_frame: 2s
        slots:
            - partition: pr1
              duration: 2s
