#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2020 POK team

target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, console, libc]
      semaphores: 1
      scheduler: static
      threads:
          count: 3
          features: [sleep]
      size: 130kB
      objects: ["main.o"]
    - name: pr2
      features: [timer, console, libc]
      semaphores: 1
      scheduler: static
      scheduler: static
      threads:
          count: 3
          features: [sleep]
      size: 130kB
      objects: ["main.o"]
    - name: pr3
      features: [console, shutdown]
      threads:
          count: 1
      size: 130kB
      objects: ["main.o"]

kernel:
    features: [assert, debug]
    scheduler:
        slots:
            - partition: pr1
              duration: 50ms
            - partition: pr2
              duration: 50ms
            - partition: pr3
              duration: 1ms
